POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username":"achrsausfsbb",
    "email":"achrafu@gsmssail.com",
    "password":"helloworld",
    "roles":["wellAdmin"]
}

###

POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username":"achrsausfsbb",
    "password":"helloworld"
}


###
GET http://localhost:8080/api/test/admin
#########
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDliOWEzNzA0NzNmYzI4ODMxZmUzNiIsImlhdCI6MTcxNjEyMjY0MywiZXhwIjoxNzE2MjA5MDQzfQ.ihscKgv1KRItXafdfOOlLRrCLCyEg0t0tR6d73xTVAw
#################
GET http://localhost:8080/well
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGI4MWVkYjYwYTU4YzkzZWZkMTRkMSIsImlhdCI6MTcxNjIyNDU4MCwiZXhwIjoxNzE2MzEwOTgwfQ.GnnmLc7Lt-e1qKQptmKX-ew84pTWBWI_pNnCLPUITTM

###### 
POST http://localhost:8080/well/create-well
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGRhYzQyODc4NzlkYWI4MTgyYmI3MSIsImlhdCI6MTcxNjM2NjQxMiwiZXhwIjoxNzE2NDUyODEyfQ.Jgj7P8yjZ4ERqj7nh6_hjGymPZHk0ksno7sybUKXZGc

{
  "name": "Well990 ",
  "attributes": [
    { "name": "gor", "value": 40 },
    { "name": "oil", "value": 500 },
    { "name": "gas", "value": 200 },
    { "name":"order_date", "value":"21-12-2001"},
    {"name":"hello","value":"vvv"},
    {"name":"islam","value":"benchiba"}

  ],
  "centre":"hassi90",
  "region":"hassi90",
  "wilaya":"batna99",
  "zone":"3299",
  "longitude": 9946.123,
  "latitude": 9945.678,
  "elevation": 19900,
  "type":"eriptif99",
  "date":"2022-12-14T00:00:00.000Z"
}

#####
POST http://localhost:8080/telemetry/create
Content-Type: application/json
 
{
    "ID":"6633d0ebb0710cd83a14a0d0",
    "date":"2022-12-14T00:00:00.000Z",
    "attributes": [
        { "name": "gor", "value": 40 },
        { "name": "oil", "value": 500 },
        { "name": "gas", "value": 200 }
    ]
}

######
GET http://localhost:8080/well
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGRhYzQyODc4NzlkYWI4MTgyYmI3MSIsImlhdCI6MTcxNjM2NjQxMiwiZXhwIjoxNzE2NDUyODEyfQ.Jgj7P8yjZ4ERqj7nh6_hjGymPZHk0ksno7sybUKXZGc

###### 
PATCH http://localhost:8080/well/6633d0ebb0710cd83a14a0d2
Content-Type: application/json

{
    "name":"edited well",
    "attributes":[
        {"name":"gor", "value": "88"},
        {"name":"oil", "value":22},
        {"name":"achraf", "value":77},
        {"name":"order_date", "value":"12-12-2001"},
        {"name":"hello", "value":"haha"}
    ]
}
########
GET http://localhost:8080/manufold

######    
POST http://localhost:8080/manufold/create-manufold
Content-Type: application/json

{
  "name": "manufold 1",
  "attributes": [
    { "name": "temp", "value": 40 },
    { "name": "press", "value": 500 },
    { "name": "kach7aja", "value": 200 },
    { "name":"order_date", "value":"21-12-2001"},
    {"name":"hello","value":"vvv"},
    {"name":"islam","value":"benchiba"}

  ],
  "centre":"centre1",
  "region":"ourgla",
  "wilaya":"hassi messoud",
  "zone":"laghouat",
  "longitude": 46.123,
  "latitude": 45.678,
  "elevation": 100
}

###### 
PATCH http://localhost:8080/manufold/6634f5f8784e71ac338103aa
Content-Type: application/json

{
    "name":"edited manufold",
    "attributes":[
        {"name":"gor", "value": "88"},
        {"name":"oil", "value":22},
        {"name":"achraf", "value":77},
        {"name":"order_date", "value":"12-12-2001"},
        {"name":"hello", "value":"haha"}
    ]
}
##########
GET http://localhost:8080/pipe
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGRhYzQyODc4NzlkYWI4MTgyYmI3MSIsImlhdCI6MTcxNjM3MDM4MywiZXhwIjoxNzE2NDU2NzgzfQ.452P17-CPu4aqXNBrlJqzfTsWkxxVKXoMStojHSdz_I
#########
POST http://localhost:8080/pipe/create-pipe
Content-Type: application/json

{
  "from_id": "6633d0ebb0710cd83a14a0d0",
  "to_id": "6633d314a75a82fe3736a184",
  "length": 100,
    "coords": [
        [ 
            { 
                "latitude": 31.788951233790343, 
                "longitude": 5.405648285672383 
            }, 
            { 
                "latitude": 31.79711946380753, 
                "longitude": 5.516862796954007 
            }, 
            { 
                "latitude": 31.72941806467556, 
                "longitude": 5.666521830653997 
            }, 
            { 
                "latitude": 31.739926700242876, 
                "longitude": 5.75988709938427 
            }, 
            { 
                "latitude": 31.694380672626355, 
                "longitude": 5.87659368529709 
            }, 
            { 
                "latitude": 31.780782282009984, 
                "longitude": 5.953482730133777 
            }, 
            { 
                "latitude": 31.82745228305688, 
                "longitude": 6.020760644365884 
            }, 
            { 
                "latitude": 31.870601037773323, 
                "longitude": 6.088038558597991 
            }, 
            { 
                "latitude": 31.911398841789094, 
                "longitude": 6.122364025042928 
            } 
        ] ],
    "connectionType": "direct",
    "type": "collect",
    "nature": "oil",
    "segments":[
        {
            "coords": [[
                { 
                    "latitude": 31.788951233790343, 
                    "longitude": 5.405648285672383 
                }, 
                { 
                    "latitude": 31.79711946380753, 
                    "longitude": 5.516862796954007 
                }, 
                { 
                    "latitude": 31.72941806467556, 
                    "longitude": 5.666521830653997 
                }
            ]],
            "attributes":[
                {"name":"gor", "value": "88"},
                {"name":"oil", "value":22},
                {"name":"achraf", "value":77},
                {"name":"order_date", "value":"12-12-2001"},
                {"name":"hello", "value":"haha"}
            ]
        },
        {
            "coords": [
                {
                "latitude": 31.72941806467556, 
                "longitude": 5.666521830653997 
                }, 
                { 
                "latitude": 31.739926700242876, 
                "longitude": 5.75988709938427 
                }, 
                { 
                "latitude": 31.694380672626355, 
                "longitude": 5.87659368529709 
                }, 
                { 
                "latitude": 31.780782282009984, 
                "longitude": 5.953482730133777 
                }, 
                { 
                "latitude": 31.82745228305688, 
                "longitude": 6.020760644365884 
                }, 
                { 
                "latitude": 31.870601037773323, 
                "longitude": 6.088038558597991 
                }, 
                { 
                "latitude": 31.911398841789094, 
                "longitude": 6.122364025042928 
                } 
            ],
            "attributes":[
                {"name":"gor", "value": "88"},
                {"name":"oil", "value":22},
                {"name":"achraf", "value":77},
                {"name":"order_date", "value":"12-12-2001"},
                {"name":"hello", "value":"haha"}
            ]
        }
    ]
}


#######
PATCH http://localhost:8080/pipe/66366749a03561767f8444b8
Content-Type: application/json

{
    "segments":[
        {
            "coords": [
                {
                    "latitude": 31.72941806467556, 
                    "longitude": 5.666521830653997 
                }, 
                { 
                    "latitude": 31.739926700242876, 
                    "longitude": 5.75988709938427 
                }, 
                { 
                    "latitude": 31.694380672626355, 
                    "longitude": 5.87659368529709 
                }
            ],
            "attributes":[
                {"name":"gor", "value": "88"},
                {"name":"oil", "value":22},
                {"name":"achraf", "value":77},
                {"name":"order_date", "value":"12-12-2001"},
                {"name":"hello", "value":"haha"}
            ]
        },
        {
            "coords": [ 
                { 
                    "latitude": 31.780782282009984, 
                    "longitude": 5.953482730133777 
                }, 
                { 
                    "latitude": 31.82745228305688, 
                    "longitude": 6.020760644365884 
                }, 
                { 
                    "latitude": 31.870601037773323, 
                    "longitude": 6.088038558597991 
                }, 
                { 
                    "latitude": 31.911398841789094, 
                    "longitude": 6.122364025042928 
                } 
            ],
            "attributes":[
                {"name":"gor", "value": "88"},
                {"name":"oil", "value":22},
                {"name":"achraf", "value":77},
                {"name":"order_date", "value":"12-12-2001"},
                {"name":"hello", "value":"haha"}
            ]
        }
    ]
}

#######
GET http://localhost:8080/pipe/66365f0abcbf716ec33b78e4/segments

########
POST http://localhost:8080/inspection/create
Content-Type: application/json

{
    "pipeID":"66365f0abcbf716ec33b78e4",
    "observation":"hello this is observation",
    "ficher":"this is attached file of the inspection",
    "Inspection_date":"12-12-2001"
}
############ 
GET http://localhost:8080/inspection


###########
###
### Upload CSV File and Create Wells
###

# POST request to upload CSV file and create wells
POST http://localhost:8080/well/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="csvFile"; filename="sample.csv"
Content-Type: text/csv

name,gor,oil,gas,order_date,attribute1,attribute2,attribute3
Well 1,40,500,200,21-12-2001,Value1.1,Value1.2,Value1.3
Well 2,35,450,180,15-10-2002,Value2.1,Value2.2,Value2.3
Well 3,42,480,190,28-05-2003,Value3.1,Value3.2,Value3.3
Well 4,38,520,220,09-08-2004,Value4.1,Value4.2,Value4.3
Well 5,41,490,200,17-03-2005,Value5.1,Value5.2,Value5.3
Well 6,36,510,210,22-11-2006,Value6.1,Value6.2,Value6.3
Well 7,39,470,195,30-07-2007,Value7.1,Value7.2,Value7.3
Well 8,37,530,225,08-04-2008,Value8.1,Value8.2,Value8.3
Well 9,43,460,185,13-01-2009,Value9.1,Value9.2,Value9.3
Well 10,34,540,230,25-06-2010,Value10.1,Value10.2,Value10.3
Well 11,45,450,175,02-03-2011,Value11.1,Value11.2,Value11.3
Well 12,32,510,210,14-09-2012,Value12.1,Value12.2,Value12.3
Well 13,47,480,195,20-05-2013,Value13.1,Value13.2,Value13.3
Well 14,31,520,220,04-10-2014,Value14.1,Value14.2,Value14.3
Well 15,48,470,190,11-02-2015,Value15.1,Value15.2,Value15.3
Well 16,30,530,225,27-07-2016,Value16.1,Value16.2,Value16.3
Well 17,49,460,180,05-12-2017,Value17.1,Value17.2,Value17.3
Well 18,29,540,230,10-08-2018,Value18.1,Value18.2,Value18.3
Well 19,50,450,175,15-03-2019,Value19.1,Value19.2,Value19.3
Well 20,28,550,235,22-10-2020,Value20.1,Value20.2,Value20.3
Well 21,51,440,170,01-06-2021,Value21.1,Value21.2,Value21.3
Well 22,27,560,240,13-12-2022,Value22.1,Value22.2,Value22.3
Well 23,52,430,165,19-07-2023,Value23.1,Value23.2,Value23.3
Well 24,26,570,245,26-02-2024,Value24.1,Value24.2,Value24.3
Well 25,53,440,170,04-09-2025,Value25.1,Value25.2,Value25.3
Well 26,25,580,250,12-04-2026,Value26.1,Value26.2,Value26.3
Well 27,54,430,165,18-11-2027,Value27.1,Value27.2,Value27.3
Well 28,24,590,255,29-05-2028,Value28.1,Value28.2,Value28.3
Well 29,55,440,170,06-01-2029,Value29.1,Value29.2,Value29.3
Well 30,23,600,260,15-08-2030,Value30.1,Value30.2,Value30.3
Well 31,56,430,165,20-03-2031,Value31.1,Value31.2,Value31.3
Well 32,22,610,265,31-10-2032,Value32.1,Value32.2,Value32.3
Well 33,57,440,170,07-06-2033,Value33.1,Value33.2,Value33.3
Well 34,21,620,270,15-01-2034,Value34.1,Value34.2,Value34.3
Well 35,58,430,165,23-08-2035,Value35.1,Value35.2,Value35.3
Well 36,20,630,275,02-04-2036,Value36.1,Value36.2,Value36.3
Well 37,59,440,170,11-11-2037,Value37.1,Value37.2,Value37.3
Well 38,19,640,280,18-07-2038,Value38.1,Value38.2,Value38.3
Well 39,60,430,165,25-02-2039,Value39.1,Value39.2,Value39.3
Well 40,18,650,285,05-09-2040,Value40.1,Value40.2,Value40.3
Well 41,61,440,170,12-04-2041,Value41.1,Value41.2,Value41.3
Well 42,17,660,290,20-11-2042,Value42.1,Value42.2,Value42.3
Well 43,62,430,165,29-06-2043,Value43.1,Value43.2,Value43.3
Well 44,16,670,295,06-02-2044,Value44.1,Value44.2,Value44.3
Well 45,63,440,170,13-09-2045,Value45.1,Value45.2,Value45.3
Well 46,15,680,300,21-05-2046,Value46.1,Value46.2,Value46.3
Well 47,64,430,165,29-12-2047,Value47.1,Value47.2,Value47.3
Well 48,14,690,305,06-08-2048,Value48.1,Value48.2,Value48.3
Well 49,65,440,170,15-03-2049,Value49.1,Value49.2,Value49.3
Well 50,13,700,310,23-10-2050,Value50.1,Value50.2,Value50.3
Well 51,66,430,165,31-05-2051,Value51.1,Value51.2,Value51.3
Well 52,12,710,315,08-01-2052,Value52.1,Value52.2,Value52.3
Well 53,67,440,170,17-08-2053,Value53.1,Value53.2,Value53.3
Well 54,11,720,320,24-03-2054,Value54.1,Value54.2,Value54.3
Well 55,68,430,165,02-11-2055,Value55.1,Value55.2,Value55.3
Well 56,10,730,325,09-06-2056,Value56.1,Value56.2,Value56.3
Well 57,69,440,170,17-01-2057,Value57.1,Value57.2,Value57.3
Well 58,9,740,330,25-08-2058,Value58.1,Value58.2,Value58.3
Well 59,70,430,165,04-04-2059,Value59.1,Value59.2,Value59.3
Well 60,8,750,335,11-11-2060,Value60.1,Value60.2,Value60.3
Well 61,71,440,170,20-05-2061,Value61.1,Value61.2,Value61.3
Well 62,7,760,340,28-12-2062,Value62.1,Value62.2,Value62.3
Well 63,72,430,165,06-08-2063,Value63.1,Value63.2,Value63.3
Well 64,6,770,345,14-03-2064,Value64.1,Value64.2,Value64.3
Well 65,73,440,170,22-09-2065,Value65.1,Value65.2,Value65.3
Well 66,5,780,350,30-04-2066,Value66.1,Value66.2,Value66.3
Well 67,74,430,165,08-12-2067,Value67.1,Value67.2,Value67.3
Well 68,4,790,355,15-07-2068,Value68.1,Value68.2,Value68.3
Well 69,75,440,170,23-02-2069,Value69.1,Value69.2,Value69.3
Well 70,3,800,360,02-10-2070,Value70.1,Value70.2,Value70.3
Well 71,76,430,165,10-04-2071,Value71.1,Value71.2,Value71.3
Well 72,2,810,365,17-11-2072,Value72.1,Value72.2,Value72.3
Well 73,77,440,170,25-05-2073,Value73.1,Value73.2,Value73.3
Well 74,1,820,370,02-01-2074,Value74.1,Value74.2,Value74.3
Well 75,78,430,165,10-08-2075,Value75.1,Value75.2,Value75.3
Well 76,0,830,375,18-03-2076,Value76.1,Value76.2,Value76.3
Well 77,79,440,170,26-10-2077,Value77.1,Value77.2,Value77.3
Well 78,-1,840,380,03-06-2078,Value78.1,Value78.2,Value78.3
Well 79,80,430,165,11-01-2079,Value79.1,Value79.2,Value79.3
Well 80,-2,850,385,19-08-2080,Value80.1,Value80.2,Value80.3
Well 81,81,440,170,27-03-2081,Value81.1,Value81.2,Value81.3
Well 82,-3,860,390,04-11-2082,Value82.1,Value82.2,Value82.3
Well 83,82,430,165,12-06-2083,Value83.1,Value83.2,Value83.3
Well 84,-4,870,395,20-01-2084,Value84.1,Value84.2,Value84.3


