POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username":"islawwm2",
    "email":"ac.bens.ssaddlem@gmail.com",
    "password":"hellowsorld",
    "roles":"admin"
}

###

POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username":"achraf",
    "password":"helloworld"
}

###
GET http://localhost:8080/api/test/admin
#########
##
POST http://localhost:8080/well/create-well
Content-Type: application/json

{
  "centre": "Sample Centre",
  "region": "Sample Region",
  "zone": "Sample Zone",
  "wilaya": "Sample Wilaya",
  "longitude": 46.123,
  "latitude": 45.678,
  "elevation": 100,
  "order_date": "2024-05-05",
  "gor": 10,
  "oil": 20,
  "gas": 30
}
#########

POST http://localhost:8080/pipe/create-pipe
Content-Type: application/json

{
  "from_id": "6633a2bff02a70c6bac82ee6",
  "to_id": "6633a2c7f02a70c6bac82eee",
  "length": 100,
  "connectionType": "direct",
  "type": "collect",
  "nature": "oil"
}

######
POST http://localhost:8080/well/create-well
Content-Type: application/json

{
  "name": "Well 5",
  "attributes": [
    { "name": "gor", "value": 40 },
    { "name": "oil", "value": 500 },
    { "name": "gas", "value": 200 },
    { "name":"order_date", "value":"21-12-2001"},
    {"name":"hello","value":"vvv"},
    {"name":"islam","value":"benchiba"}

  ],
  "centre":"blahhhbal",
  "region":"blahhbla",
  "wilaya":"blahhhblbaa",
  "zone":"blbhhhlb",
  "longitude": 46.123,
  "latitude": 45.678,
  "elevation": 100
}



######    
POST http://localhost:8080/manufold/create-manufold
Content-Type: application/json

{
  "name": "manufold 1",
  "attributes": [
    { "name": "temp", "value": 40 },
    { "name": "press", "value": 500 },
    { "name": "kach7aja", "value": 200 },
    { "name":"order_date", "value":"21-12-2001"},
    {"name":"hello","value":"vvv"},
    {"name":"islam","value":"benchiba"}

  ],
  "centre":"blahhhbal",
  "region":"blahhbla",
  "wilaya":"blahhhblbaa",
  "zone":"blbhhhlb",
  "longitude": 46.123,
  "latitude": 45.678,
  "elevation": 100
}
