POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username":"islawwm2",
    "email":"ac.bens.ssaddlem@gmail.com",
    "password":"hellowsorld",
    "roles":"admin"
}

###

POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username":"achraf",
    "password":"helloworld"
}

###
GET http://localhost:8080/api/test/admin
#########
##
POST http://localhost:8080/well/create-well
Content-Type: application/json

{
  "centre": "Sample Centre",
  "region": "Sample Region",
  "zone": "Sample Zone",
  "wilaya": "Sample Wilaya",
  "longitude": 46.123,
  "latitude": 45.678,
  "elevation": 100,
  "order_date": "2024-05-05",
  "gor": 10,
  "oil": 20,
  "gas": 30
}
#########

POST http://localhost:8080/pipe/create-pipe
Content-Type: application/json

{
  "from_id": "6633d0ebb0710cd83a14a0d0",
  "to_id": "6633d314a75a82fe3736a184",
  "length": 100,
  "coords": [
    {
      "longitude": 51.5074,
      "latitude": -0.1278,
      "elevation": 15
    },
    {
      "longitude": -33.8688,
      "latitude": 151.2093,
      "elevation": 25
    },
    {
      "longitude": 51.5074,
      "latitude": -0.1278,
      "elevation": 15
    },
    {
      "longitude": -33.8688,
      "latitude": 151.2093,
      "elevation": 25
    },
    {
      "longitude": 51.5074,
      "latitude": -0.1278,
      "elevation": 15
    },
    {
      "longitude": -33.8688,
      "latitude": 151.2093,
      "elevation": 25
    }
  ],
  "connectionType": "direct",
  "type": "collect",
  "nature": "oil"
}

######
POST http://localhost:8080/well/create-well
Content-Type: application/json

{
  "name": "Well 5",
  "attributes": [
    { "name": "gor", "value": 40 },
    { "name": "oil", "value": 500 },
    { "name": "gas", "value": 200 },
    { "name":"order_date", "value":"21-12-2001"},
    {"name":"hello","value":"vvv"},
    {"name":"islam","value":"benchiba"}

  ],
  "centre":"blahhhbal",
  "region":"blahhbla",
  "wilaya":"blahhhblbaa",
  "zone":"blbhhhlb",
  "longitude": 46.123,
  "latitude": 45.678,
  "elevation": 100
}

###### 
PATCH http://localhost:8080/well/6633d0ebb0710cd83a14a0d2
Content-Type: application/json

{
    "name":"edited well",
    "attributes":[
        {"name":"gor", "value": "88"},
        {"name":"oil", "value":22},
        {"name":"achraf", "value":77},
        {"name":"order_date", "value":"12-12-2001"},
        {"name":"hello", "value":"haha"}
    ]
}

######    
POST http://localhost:8080/manufold/create-manufold
Content-Type: application/json

{
  "name": "manufold 1",
  "attributes": [
    { "name": "temp", "value": 40 },
    { "name": "press", "value": 500 },
    { "name": "kach7aja", "value": 200 },
    { "name":"order_date", "value":"21-12-2001"},
    {"name":"hello","value":"vvv"},
    {"name":"islam","value":"benchiba"}

  ],
  "centre":"blahhhbal",
  "region":"blahhbla",
  "wilaya":"blahhhblbaa",
  "zone":"blbhhhlb",
  "longitude": 46.123,
  "latitude": 45.678,
  "elevation": 100
}

###### 
PATCH http://localhost:8080/manufold/6634f5f8784e71ac338103aa
Content-Type: application/json

{
    "name":"edited manufold",
    "attributes":[
        {"name":"gor", "value": "88"},
        {"name":"oil", "value":22},
        {"name":"achraf", "value":77},
        {"name":"order_date", "value":"12-12-2001"},
        {"name":"hello", "value":"haha"}
    ]
}
